/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-06 02:00:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.oop.model.Admin;
import java.util.ArrayList;
import com.oop.service.AdminServiceImpl;
import com.oop.service.IAdmintService;

public final class ListAdmins_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar", Long.valueOf(1381923344000L));
    _jspx_dependants.put("jar:file:/F:/ishuuuuuuuuuuuuuuuuuuuuu/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/AdminWebApp/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar!/META-INF/c.tld", Long.valueOf(1323238578000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.oop.service.IAdmintService");
    _jspx_imports_classes.add("com.oop.model.Admin");
    _jspx_imports_classes.add("com.oop.service.AdminServiceImpl");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel = \"stylesheet\"\r\n");
      out.write("   type = \"text/css\"\r\n");
      out.write("   href = \"Admin.css\" />\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>SLIIT OOP Admin Management</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h3>List of Admins</h3>\r\n");
      out.write("\tSLIIT Admin Management App for OOP jsp servlet.\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t  <div align=\"left\">\r\n");
      out.write("\t\t<table border=\"1\" cellpadding=\"12\">\r\n");
      out.write("\t\t <caption><h2>List of Admins</h2></caption>\r\n");
      out.write("\t\t <a href=\"homeView.jsp\">Add Admin</a>\r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("                <th>Index Number</th>\r\n");
      out.write("                <th>Customer ID</th>\r\n");
      out.write("                <th>Customer Name</th>\r\n");
      out.write("                <th>Driver Name</th>\r\n");
      out.write("                <th>Vehicle Number</th>\r\n");
      out.write("                <th>Amount</th>\r\n");
      out.write("                <th>Select</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("            ");

            	IAdmintService iAdminService = new AdminServiceImpl();
                                                                        	ArrayList<Admin> arrayList = iAdminService.getAdmins();
                                                                        	
                                                                       	for(Admin admin : arrayList){
             
      out.write("                                          \t\t\r\n");
      out.write("\t\t\t <tr>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print(admin.getIndexID() );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print(admin.getCustermorID() );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print(admin.getCustemorName() );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print(admin.getDriverName() );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print(admin.getVehicleNumber() );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print(admin.getAmount() );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<td> \r\n");
      out.write("\t\t\t\t<form method=\"POST\" action=\"GetAdminServlet\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"indexID\" value=\"");
      out.print(admin.getIndexID());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t <input type=\"submit\" value= \"Select Admin\" class=\"select-button\" /> \r\n");
      out.write("\t\t\t\t </form>\r\n");
      out.write("\t\t\t\t </td>\t\r\n");
      out.write("\t\t\t\t</tr>\t\t\t\r\n");
      out.write("\t\t\t");
	
			   }
            
      out.write("     \r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
